
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

# ===== CONEX\u00c3O COM O BANCO =====
spring.datasource.url=jdbc:mysql://localhost/prg03_gerenciamento_curso?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA/HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== NECESS\u00c1RIO PARA SWING (DESKTOP) =====
spring.main.headless=false
