/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import java.awt.HeadlessException;

/**
 *
 * @author Italo
 */
public final class CursoListar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public CursoListar() {
        initComponents();
        configurarTabela();  // configura as colunas
        carregarCursos();    // carrega dados do banco
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        jButton1.setText("+");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jButton2.setText("Homescreen");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 23, 110, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Quantidade", "Descrição", "Fornecedor", "Remover", "Editar"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 460, 230));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 460, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new CursoForm(this, null).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
 * Configura as colunas da tabela
 */
private void configurarTabela() {
    // Define as colunas da JTable gerada pelo Designer
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {},
        new String[] {"ID", "Nome", "Código", "Ativo", "Remover", "Editar"}
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Nenhuma célula editável diretamente
        }
    });

    // Clique na linha para Remover ou Editar
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            int linha = jTable1.getSelectedRow();
            int coluna = jTable1.getSelectedColumn();

            if (linha >= 0) {
                Long id = (Long) jTable1.getModel().getValueAt(linha, 0);

                if (coluna == 4) {
                    removerCurso(id); // Coluna Remover
                } else if (coluna == 5) {
                    editarCurso(id);  // Coluna Editar
                }
            }
        }
    });
}

/**
 * Busca todos os cursos no banco via JPQL e preenche a tabela
 */
public void carregarCursos() {
    jakarta.persistence.EntityManager em = br.com.ifba.CursoSave.getEntityManager();

    try {
        // JPQL — lista todos os cursos
        java.util.List<br.com.ifba.curso.entity.Curso> cursos = em
            .createQuery("select c from Curso as c", br.com.ifba.curso.entity.Curso.class)
            .getResultList();

        // Pega o modelo da tabela e limpa
        javax.swing.table.DefaultTableModel modelo =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);

        // Adiciona cada curso na tabela
        for (br.com.ifba.curso.entity.Curso c : cursos) {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getCodigoCurso(),
                c.isAtivo() ? "Sim" : "Não",
                "🗑 Remover",
                "✏ Editar"
            });
        }

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Erro ao carregar cursos: " + ex.getMessage(),
            "Erro",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

/**
 * Remove o curso do banco pelo ID com confirmação
 */
private void removerCurso(Long id) {
    int resposta = javax.swing.JOptionPane.showConfirmDialog(this,
        "Deseja realmente excluir este curso?",
        "Confirmar exclusão",
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (resposta == javax.swing.JOptionPane.YES_OPTION) {
        jakarta.persistence.EntityManager em = br.com.ifba.CursoSave.getEntityManager();

        try {
            em.getTransaction().begin();

            // Busca antes de remover (conforme o slide do professor)
            br.com.ifba.curso.entity.Curso curso =
                em.find(br.com.ifba.curso.entity.Curso.class, id);

            em.remove(curso);
            em.getTransaction().commit();

            javax.swing.JOptionPane.showMessageDialog(this,
                "Curso removido com sucesso!", "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            carregarCursos(); // Atualiza a tabela

        } catch (Exception ex) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            javax.swing.JOptionPane.showMessageDialog(this,
                "Erro ao remover: " + ex.getMessage(), "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
}

/**
 * Busca o curso e abre o formulário de edição
 */
private void editarCurso(Long id) {
    jakarta.persistence.EntityManager em = br.com.ifba.CursoSave.getEntityManager();

    try {
        br.com.ifba.curso.entity.Curso curso =
            em.find(br.com.ifba.curso.entity.Curso.class, id);

        if (curso != null) {
            new CursoForm(this, curso).setVisible(true);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Curso não encontrado!", "Atenção",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        }

    } catch (HeadlessException ex) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Erro ao buscar curso: " + ex.getMessage(), "Erro",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
}
